baseURL = "https://florianwechsung.github.io/"
languageCode = "en-uk"
title = "Florian Wechsung"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
#googleAnalytics = ""

[params]
    author = "Florian Wechsung"
    description = "Personal website"
    githubUsername = "#"
    accent = "blue"
    showBorder = false
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["Python"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/publications/"
    name = "Publications"
    weight = 2

[[menu.main]]
    url = "/teaching/"
    name = "Teaching"
    weight = 3
#
#[[menu.main]]
#    url = "/project/"
#    name = "Projects"
#    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:wechsung@nyu.edu"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/florianwechsung/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://scholar.google.co.uk/citations?user=7iyeV6cAAAAJ"
    name = "google"
    weight = 3

#[[menu.icon]]
#    url = "https://twitter.com/username/"
#    name = "twitter"
#    weight = 3
#
#[[menu.icon]]
#    url = "https://www.linkedin.com/in/username/"
#    name = "linkedin"
#    weight = 4
#
#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "stack-overflow"
#    weight = 5
